# Generated by Django 4.2.16 on 2024-10-12 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('registration_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=1)),
                ('branch', models.CharField(choices=[('cse', 'CSE'), ('ct', 'CT'), ('aids', 'AIDS')], max_length=10)),
                ('mentoring_preferences', models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee')], max_length=10)),
                ('previous_mentoring_experience', models.TextField(blank=True, null=True)),
                ('tech_stack', models.TextField()),
                ('areas_of_interest', models.TextField()),
                ('published_research_papers', models.CharField(choices=[('International', 'International'), ('National', 'National'), ('College', 'College'), ('Conferences', 'Conferences'), ('None', 'None')], default='None', max_length=15)),
                ('proof_of_research_publications', models.BinaryField(blank=True, null=True)),
                ('hackathon_participation', models.CharField(choices=[('International', 'International'), ('National', 'National'), ('College', 'College'), ('Conferences', 'Conferences'), ('None', 'None')], max_length=50)),
                ('number_of_wins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_participations', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hackathon_role', models.CharField(choices=[('team leader', 'Team Leader'), ('member', 'Member')], max_length=20)),
                ('proof_of_hackathon_participation', models.BinaryField(blank=True, null=True)),
                ('coding_competitions_participate', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('level_of_competition', models.CharField(choices=[('International', 'International'), ('National', 'National'), ('College', 'College'), ('Conferences', 'Conferences'), ('None', 'None')], max_length=15)),
                ('number_of_coding_competitions', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('proof_of_coding_competitions', models.BinaryField(blank=True, null=True)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('sgpa', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('proof_of_academic_performance', models.BinaryField(blank=True, null=True)),
                ('internship_experience', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('number_of_internships', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('internship_description', models.TextField(blank=True, null=True)),
                ('proof_of_internships', models.BinaryField(blank=True, null=True)),
                ('seminars_or_workshops_attended', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('describe_seminars_or_workshops', models.TextField(blank=True, null=True)),
                ('extracurricular_activities', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('describe_extracurricular_activities', models.TextField(blank=True, null=True)),
                ('proof_of_extracurricular_activities', models.BinaryField(blank=True, null=True)),
                ('short_term_goals', models.TextField(blank=True, null=True)),
                ('long_term_goals', models.TextField(blank=True, null=True)),
                ('strengths_and_weaknesses', models.TextField(blank=True, null=True)),
                ('preferred_learning_style', models.CharField(choices=[('Hands_on', 'Hands-on'), ('Project_based', 'Project-based'), ('Discuss_oriented', 'Discuss-oriented')], max_length=20)),
                ('areas_for_personal_growth', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
