# Generated by Django 4.2.16 on 2024-10-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_mentee', '0002_alter_participant_extracurricular_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='hackathon_role',
            field=models.CharField(blank=True, choices=[('team leader', 'Team Leader'), ('member', 'Member')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='level_of_competition',
            field=models.CharField(blank=True, choices=[('International', 'International'), ('National', 'National'), ('College', 'College'), ('Conferences', 'Conferences'), ('None', 'None')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='seminars_or_workshops_attended',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default=None, max_length=3, null=True),
        ),
    ]
