# Generated by Django 4.2.16 on 2024-10-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_student_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Linkedin_Acess_token',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
