# Generated by Django 4.2.16 on 2024-10-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_student_linkedin_acess_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Linkedin_Acess_token',
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin_access_token',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
