# Generated by Django 4.2.16 on 2024-10-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_student_linkedin_acess_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='linkedin_access_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
